package com.moskao4.musicdownloader;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.concurrent.Executors;
import java.util.regex.*;

public class MainActivity extends Activity {
    LinearLayout root, content; EditText input; TextView title,status,progressText; ProgressBar progress;
    android.content.SharedPreferences prefs;
    int themeMode; // 0 system, 1 light, 2 dark, 3 colorful
    final int BG_DARK=Color.rgb(15,15,17), FG=Color.WHITE, MUTED=Color.rgb(160,160,165), ACCENT=Color.rgb(210,175,40);
    final int[] ICONS={1,2,3,4,5,6,7,8,9};

    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("settings",0); themeMode=prefs.getInt("theme",2); applyTheme(); buildMain();}
    void applyTheme(){ getWindow().setStatusBarColor(BG_DARK); getWindow().setNavigationBarColor(BG_DARK); }
    int effectiveTheme(){ if(themeMode==0){ int ui=getResources().getConfiguration().uiMode & android.content.res.Configuration.UI_MODE_NIGHT_MASK; return ui==android.content.res.Configuration.UI_MODE_NIGHT_YES?2:1;} return themeMode; }
    int bg(){ int t=effectiveTheme(); if(t==1)return Color.rgb(247,247,249); if(t==3)return Color.rgb(20,17,30); return BG_DARK; }
    int fg(){ return effectiveTheme()==1?Color.rgb(25,25,28):Color.WHITE; }
    int muted(){return effectiveTheme()==1?Color.rgb(105,105,112):MUTED;}
    Button btn(String s){ Button x=new Button(this); x.setText(s); x.setTextColor(fg()); x.setTextSize(15); x.setAllCaps(false); x.setBackgroundColor(themeMode==3?Color.rgb(90,55,150):Color.rgb(40,40,44)); return x; }
    TextView tv(String s,float size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(fg());t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(18,8,18,8);return t;}
    void base(){ root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg());
        LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(8,8,12,8);bar.setBackgroundColor(bg());
        TextView menu=tv("☰",30);menu.setGravity(Gravity.CENTER);menu.setOnClickListener(v->showDrawer());bar.addView(menu,new LinearLayout.LayoutParams(58,64));
        title=tv("网易云下载",20);title.setGravity(Gravity.CENTER);bar.addView(title,new LinearLayout.LayoutParams(0,64,1));
        TextView about=tv("⋮",28);about.setGravity(Gravity.CENTER);about.setOnClickListener(v->showAbout());bar.addView(about,new LinearLayout.LayoutParams(52,64));root.addView(bar);
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(24,28,24,24);root.addView(content,new LinearLayout.LayoutParams(-1,0,1)); setContentView(root); }
    void buildMain(){base();
        TextView hint=tv("网易云音乐",14);hint.setTextColor(muted());hint.setGravity(Gravity.CENTER);content.addView(hint,new LinearLayout.LayoutParams(-1,44));
        input=new EditText(this);input.setHint("粘贴网易云分享文本或链接");input.setTextColor(fg());input.setHintTextColor(muted());input.setTextSize(16);input.setSingleLine(false);input.setMinHeight(120);input.setGravity(Gravity.TOP|Gravity.START);input.setPadding(18,18,18,18);content.addView(input,new LinearLayout.LayoutParams(-1,140));
        Button go=btn("开始下载");go.setOnClickListener(v->startNetease());LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,58);gp.topMargin=18;content.addView(go,gp);
        progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setVisibility(View.GONE);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,8);pp.topMargin=24;content.addView(progress,pp);
        progressText=tv("",13);progressText.setTextColor(muted());content.addView(progressText,new LinearLayout.LayoutParams(-1,45));
        status=tv("● 等待输入",14);status.setTextColor(muted());content.addView(status,new LinearLayout.LayoutParams(-1,55));
    }
    void showDrawer(){ final Dialog d=new Dialog(this); d.getWindow(); LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(20,30,20,20);box.setBackgroundColor(bg());
        TextView h=tv("音乐下载器",24);h.setPadding(20,20,20,28);box.addView(h);
        addMenu(box,"⌕  综合搜索",()->{d.dismiss();showSearch();}); addMenu(box,"☁  网易云下载",()->{d.dismiss();buildMain();}); addMenu(box,"♫  QQ 音乐",()->{d.dismiss();showQQ();}); addMenu(box,"↧  普通下载",()->{d.dismiss();showNormal();}); addMenu(box,"▣  下载记录",()->{d.dismiss();showHistory();});
        Space sp=new Space(this);box.addView(sp,new LinearLayout.LayoutParams(1,0,1)); addMenu(box,"⚙  设置",()->{d.dismiss();showSettings();}); addMenu(box,"ⓘ  关于",()->{d.dismiss();showAbout();});
        d.setContentView(box);Window w=d.getWindow(); if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.82),-1);w.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);} d.show(); if(w!=null)w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.82),-1);
    }
    void addMenu(LinearLayout box,String s,final Runnable r){Button b=btn(s);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setPadding(24,0,12,0);b.setOnClickListener(v->r.run());box.addView(b,new LinearLayout.LayoutParams(-1,58));}
    void showSearch(){base();title.setText("综合搜索"); input=new EditText(this);input.setHint("输入歌曲名");input.setTextColor(fg());input.setHintTextColor(muted());input.setSingleLine();content.addView(input,new LinearLayout.LayoutParams(-1,60));Button b=btn("搜索");content.addView(b,new LinearLayout.LayoutParams(-1,56));TextView info=tv("搜索结果会在这里展示。\n\n当前版本优先完成网易云真实下载；QQ 音乐接口正在接入。",15);info.setTextColor(muted());info.setPadding(8,30,8,8);content.addView(info,new LinearLayout.LayoutParams(-1,-2));}
    void showQQ(){base();title.setText("QQ 音乐"); input=new EditText(this);input.setHint("粘贴 QQ 音乐分享链接");input.setTextColor(fg());input.setHintTextColor(muted());content.addView(input,new LinearLayout.LayoutParams(-1,120));Button b=btn("识别链接");content.addView(b,new LinearLayout.LayoutParams(-1,56));status=tv("● 等待输入",14);content.addView(status);b.setOnClickListener(v->{Matcher m=Pattern.compile("songmid=([A-Za-z0-9]+)").matcher(input.getText().toString());status.setText(m.find()?"● 已识别 SongMID："+m.group(1)+"\n实际音频地址解析尚未启用":"● 未找到 songmid");});}
    void showNormal(){base();title.setText("普通下载");input.setHint("粘贴音频文件 URL");content.addView(input,new LinearLayout.LayoutParams(-1,120));Button b=btn("开始下载");content.addView(b,new LinearLayout.LayoutParams(-1,56));progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setVisibility(View.GONE);content.addView(progress,new LinearLayout.LayoutParams(-1,8));progressText=tv("",13);progressText.setTextColor(muted());content.addView(progressText,new LinearLayout.LayoutParams(-1,45));status=tv("● 等待输入",14);content.addView(status);b.setOnClickListener(v->startUrlDownload(input.getText().toString().trim(),"audio.mp3"));}
    void showHistory(){base();title.setText("下载记录");String h=prefs.getString("history","");TextView t=tv(h.isEmpty()?"暂无下载记录":h,15);t.setTextColor(muted());content.addView(t,new LinearLayout.LayoutParams(-1,-2));}
    void showSettings(){base();title.setText("设置");
        TextView a=tv("外观",17);a.setPadding(8,24,8,8);content.addView(a);RadioGroup rg=new RadioGroup(this);String[] ns={"跟随系统","浅色","深色","炫彩"};for(int i=0;i<4;i++){RadioButton r=new RadioButton(this);r.setText(ns[i]);r.setTextColor(fg());r.setTextSize(16);r.setChecked(themeMode==i);final int z=i;r.setOnClickListener(v->{themeMode=z;prefs.edit().putInt("theme",z).apply();showSettings();});rg.addView(r,new RadioGroup.LayoutParams(-1,52));}content.addView(rg);
        TextView ic=tv("应用图标",17);ic.setPadding(8,24,8,8);content.addView(ic);GridLayout grid=new GridLayout(this);grid.setColumnCount(3);for(int i=1;i<=9;i++){ImageButton ib=new ImageButton(this);ib.setImageResource(getIcon(i));ib.setBackgroundColor(Color.TRANSPARENT);final int z=i;ib.setContentDescription("图标 "+i);ib.setOnClickListener(v->changeIcon(z));grid.addView(ib,new ViewGroup.LayoutParams(100,100));}content.addView(grid);TextView cur=tv("当前图标：0"+prefs.getInt("icon",6),14);cur.setTextColor(muted());content.addView(cur);}
    int getIcon(int i){return getResources().getIdentifier("icon"+String.format(Locale.US,"%02d",i),"drawable",getPackageName());}
    void changeIcon(int n){prefs.edit().putInt("icon",n).apply();String pkg=getPackageName();PackageManager pm=getPackageManager();for(int i=1;i<=9;i++){String cn=pkg+".Icon0"+i;pm.setComponentEnabledSetting(new ComponentName(pkg,cn),i==n?PackageManager.COMPONENT_ENABLED_STATE_ENABLED:PackageManager.COMPONENT_ENABLED_STATE_DISABLED,PackageManager.DONT_KILL_APP);}Toast.makeText(this,"应用图标已切换为 0"+n,Toast.LENGTH_SHORT).show();}
    void showAbout(){base();title.setText("关于");LinearLayout center=new LinearLayout(this);center.setOrientation(LinearLayout.VERTICAL);center.setGravity(Gravity.CENTER_HORIZONTAL);center.setPadding(20,20,20,10);ImageView app=new ImageView(this);app.setImageResource(getIcon(prefs.getInt("icon",6)));app.setScaleType(ImageView.ScaleType.CENTER_INSIDE);center.addView(app,new LinearLayout.LayoutParams(120,120));TextView name=tv("音乐下载器",25);name.setGravity(Gravity.CENTER);center.addView(name,new LinearLayout.LayoutParams(-1,52));TextView ver=tv("Version 1.0",16);ver.setTextColor(muted());ver.setGravity(Gravity.CENTER);center.addView(ver,new LinearLayout.LayoutParams(-1,40));content.addView(center,new LinearLayout.LayoutParams(-1,220));addAvatarPerson(com.moskao4.musicdownloader.R.drawable.avatar_moskao4,"moskao4","作者");addChatGPTPerson();TextView foot=tv("本应用由 moskao4 与 ChatGPT 共同构思。\n音乐下载功能仅用于用户有权访问或下载的内容。",13);foot.setTextColor(muted());foot.setGravity(Gravity.CENTER);content.addView(foot,new LinearLayout.LayoutParams(-1,-2));}
    void addAvatarPerson(int imageRes,String name,String role){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(20,10,20,10);ImageView av=new ImageView(this);av.setImageResource(imageRes);av.setScaleType(ImageView.ScaleType.CENTER_CROP);android.graphics.drawable.GradientDrawable gd=new android.graphics.drawable.GradientDrawable();gd.setShape(android.graphics.drawable.GradientDrawable.OVAL);av.setBackground(gd);av.setClipToOutline(true);if(Build.VERSION.SDK_INT>=21)av.setOutlineProvider(new ViewOutlineProvider(){public void getOutline(View v,android.graphics.Outline o){o.setOval(0,0,v.getWidth(),v.getHeight());}});row.addView(av,new LinearLayout.LayoutParams(58,58));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView n=tv(name,18);TextView r=tv(role,13);r.setTextColor(muted());tx.addView(n);tx.addView(r);row.addView(tx,new LinearLayout.LayoutParams(0,70,1));content.addView(row,new LinearLayout.LayoutParams(-1,82));}
    void addChatGPTPerson(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(20,10,20,10);TextView av=tv("◉",24);av.setGravity(Gravity.CENTER);av.setTextColor(fg());av.setBackgroundColor(effectiveTheme()==1?Color.rgb(235,235,238):Color.rgb(35,35,38));row.addView(av,new LinearLayout.LayoutParams(58,58));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView n=tv("ChatGPT",18);TextView r=tv("AI 协作者",13);r.setTextColor(muted());tx.addView(n);tx.addView(r);row.addView(tx,new LinearLayout.LayoutParams(0,70,1));content.addView(row,new LinearLayout.LayoutParams(-1,82));}
    void addPerson(String avatar,String name,String role,boolean chat){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(20,10,20,10);TextView av=tv(avatar,24);av.setGravity(Gravity.CENTER);av.setBackgroundColor(Color.rgb(80,80,84));row.addView(av,new LinearLayout.LayoutParams(58,58));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView n=tv(name,18);TextView r=tv(role,13);r.setTextColor(muted());tx.addView(n);tx.addView(r);row.addView(tx,new LinearLayout.LayoutParams(0,70,1));content.addView(row,new LinearLayout.LayoutParams(-1,82));}

    void startNetease(){String s=input.getText().toString().trim();Matcher id=Pattern.compile("song\\?id=(\\d+)").matcher(s);if(!id.find()){Toast.makeText(this,"没有识别到网易云歌曲 ID",Toast.LENGTH_SHORT).show();return;}String sid=id.group(1);String name="网易云歌曲";Matcher nm=Pattern.compile("《\\s*([^《》\\r\\n]+?)(?:（|\\(|》)").matcher(s);if(nm.find())name=nm.group(1).trim();name=name.replaceAll("[\\\\/:*?\"<>|]","_");String url="https://music.163.com/song/media/outer/url?id="+sid;status.setText("● 正在获取音频："+name);startUrlDownload(url,name+".mp3");}
    void startUrlDownload(String url,String filename){if(url.isEmpty()){Toast.makeText(this,"请输入链接",Toast.LENGTH_SHORT).show();return;} if(Build.VERSION.SDK_INT<29 && checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},9);return;} progress.setVisibility(View.VISIBLE);progress.setProgress(0);status.setText("● 下载中");progressText.setText("准备连接…");Executors.newSingleThreadExecutor().execute(()->{String err=null;long total=0;try{URL u=new URL(url);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setInstanceFollowRedirects(true);c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","Mozilla/5.0");int code=c.getResponseCode();if(code<200||code>=400)throw new IOException("HTTP "+code);String ct=c.getContentType();if(ct!=null && !ct.toLowerCase(Locale.US).contains("audio") && !ct.toLowerCase(Locale.US).contains("octet-stream")){throw new IOException("服务器返回的不是音频文件");}long len=c.getContentLengthLong();InputStream in=new BufferedInputStream(c.getInputStream());OutputStream out;Uri uri=null;if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,filename);v.put(MediaStore.Downloads.MIME_TYPE,"audio/mpeg");v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS);v.put(MediaStore.Downloads.IS_PENDING,1);uri=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(uri==null)throw new IOException("无法创建 Download 文件");out=getContentResolver().openOutputStream(uri);}else{File dir=Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);if(!dir.exists())dir.mkdirs();out=new FileOutputStream(new File(dir,filename));}byte[] buf=new byte[8192];int n;long done=0;long start=System.currentTimeMillis();while((n=in.read(buf))!=-1){out.write(buf,0,n);done+=n;total=done;long elapsed=Math.max(1,System.currentTimeMillis()-start);final int pct=len>0?(int)(done*100/len):0;final double kb=done*1000.0/elapsed/1024.0;runOnUiThread(()->{progress.setProgress(pct);progressText.setText(String.format(Locale.US,"%d%% · %.1f KB/s",pct,kb));});}out.close();in.close();if(uri!=null){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.IS_PENDING,0);getContentResolver().update(uri,v,null,null);}saveHistory(filename);runOnUiThread(()->{status.setText("● 下载完成："+filename);Toast.makeText(this,"已保存到 Download/"+filename,Toast.LENGTH_LONG).show();});}catch(Exception e){err=e.getMessage();String ee=err;runOnUiThread(()->status.setText("● 下载失败："+ee));}});}
    void saveHistory(String filename){String old=prefs.getString("history","");String line="♪ "+filename+"\n   音乐下载器 · MP3\n\n";prefs.edit().putString("history",line+old).apply();}
}

class DrawerLayoutLike extends LinearLayout { public DrawerLayoutLike(android.content.Context c){super(c);} }
